Refactored blackboard examples

diff --git a/blackboard/controller-examples/run_sequencer_general b/blackboard/controller-examples/run_sequencer_general
--- a/blackboard/controller-examples/run_sequencer_general
+++ b/blackboard/controller-examples/run_sequencer_general
@@ -1,14 +1,28 @@
 #!/bin/bash
 # Start Elk JUCE example
 
-sushi -r --multicore-processing=2 -c ./sushi-configs/obxd_step.json &
+OBXD_PLUGIN_PATH=/udata/elk-examples/plugins/Obxd.so
 
+if ! test -f "$OBXD_PLUGIN_PATH"; then
+    echo "Error! Plugin OB-Xd is missing. Please download the plugin and place it\
+ in /udata/elk-examples/plugins/ . The plugin can be found at\
+ https://github.com/elk-community/OB-Xd/releases"
+    exit 0
+fi
+
+MIDI_KEYBOARD="$(aconnect -l)"
+if ! echo "$MIDI_KEYBOARD" | grep -q "16"; then
+    echo "Error! Midi Keyboard not connected. Please connect a midi keyboard"
+    exit 0
+fi
+
+./stop
+sleep 1
 sudo systemctl start sensei
-
+sleep 1
+sushi -r --multicore-processing=2 -c ./sushi-configs/obxd_step.json &
+sleep 1
 (cd ./apps; ./main_app_general &)
-
 sleep 3
-
+aconnect -x
 aconnect 16 128
-
-
